GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODcwMDQ2NTJ9.tikHW-OFpocNU-op10YawHYHeqt5NqBYVM4bw1SJ5cY
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Kyle"
}