GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Priyanshu",
    "Password":"Kanha@123"
}

###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "name":"Priyanshu",
    "Password":"Kanha@123"
}